<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>author</key>
	<string>Alex Armstrong (@alehandrof)</string>
	<key>fileTypes</key>
	<array>
		<string>.markdown</string>
		<string>.md</string>
		<string>.mdown</string>
		<string>.mdwn</string>
		<string>.mkd</string>
		<string>.mkdn</string>
		<string>.text</string>
		<string>.txt</string>
	</array>
	<key>name</key>
	<string>Markdown (Typewriter)</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#block</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#inline</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>addition</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.inserted.criticmarkup</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>markup.inserted.criticmarkup</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.inserted.criticmarkup</string>
				</dict>
			</dict>
			<key>match</key>
			<string>({\+\+)(.*?)(\+\+})</string>
			<key>name</key>
			<string>meta.addition.criticmarkup</string>
		</dict>
		<key>at-tag</key>
		<dict>
			<key>match</key>
			<string>(?&lt;=^|\s)(#)[\w\d-]+</string>
			<key>name</key>
			<string>color.green markup.tag.hash.markdo</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#tag-optional-value</string>
				</dict>
			</array>
		</dict>
		<key>atx-heading</key>
		<dict>
			<key>begin</key>
			<string>^(#{1,6})\s+(?=\S)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.heading.markdown</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(\s+#+)?(?=\n)</string>
			<key>name</key>
			<string>markup.heading.markdown</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#inline</string>
				</dict>
			</array>
		</dict>
		<key>backslash-escape</key>
		<dict>
			<key>match</key>
			<string>\\[\\`\*_{}\[\]\(\)#\+-\.!]</string>
			<key>name</key>
			<string>constant.character.escape.backslash</string>
		</dict>
		<key>block</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#horizontal-rule</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#list</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#code</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#heading</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#blockquote</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#link-definition</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#table</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#paragraph</string>
				</dict>
			</array>
		</dict>
		<key>blockquote</key>
		<dict>
			<key>begin</key>
			<string>^[ ]{0,3}(&gt;)\s*</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.markup.quote.markdown</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(\n|$)</string>
			<key>name</key>
			<string>markup.quote.markdown</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#inline</string>
				</dict>
			</array>
		</dict>
		<key>bold</key>
		<dict>
			<key>begin</key>
			<string>(\*\*|__)(.*?)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.bold.markdown</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>**bold** or __strong__</string>
			<key>end</key>
			<string>(\1)</string>
			<key>name</key>
			<string>markup.bold.markdown</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#inline</string>
				</dict>
			</array>
		</dict>
		<key>code</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#fenced-code</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#indented-code</string>
				</dict>
			</array>
		</dict>
		<key>comment</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.criticmarkup</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>markup.comment.criticmarkup</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.criticmarkup</string>
				</dict>
			</dict>
			<key>match</key>
			<string>({&gt;&gt;)(.*?)(&lt;&lt;})</string>
			<key>name</key>
			<string>meta.comment.criticmarkup</string>
		</dict>
		<key>critic-markup</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#addition</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#deletion</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#substitution</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#highlight</string>
				</dict>
			</array>
		</dict>
		<key>deletion</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.deleted.criticmarkup</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>markup.deleted.criticmarkup</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.deleted.criticmarkup</string>
				</dict>
			</dict>
			<key>match</key>
			<string>({--)(.*?)(--})</string>
			<key>name</key>
			<string>meta.deletion.criticmarkup</string>
		</dict>
		<key>etcetera</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>comment</key>
					<string>+2011-11-11 x2012-12-12</string>
					<key>match</key>
					<string>(?&lt;=^|\s)(\+|x|\.)([-\d]+)(?=\s|\n|$)</string>
					<key>name</key>
					<string>comment meta.tag.markdo</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.bracket-link.markdown</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>markup.underline.bracket-link.markdown</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.bracket-link.markdown</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>[[Search for this in Goto Anywhere]]</string>
					<key>match</key>
					<string>(\[\[)(.+?)(\]\])</string>
					<key>name</key>
					<string>color.purple markup.underline.link meta.bracket-link.markdown</string>
				</dict>
				<dict>
					<key>match</key>
					<string>([A-Z][A-Z ]{1,}[A-Z])</string>
					<key>name</key>
					<string>markup.all-caps</string>
				</dict>
			</array>
		</dict>
		<key>fenced-code</key>
		<dict>
			<key>begin</key>
			<string>^(`{3,}|~{3,})(\S*)?\s*$</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.raw.block.fenced.markdown</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>variable.syntax.raw.block.fenced.markdown</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(\1)(?=\n)</string>
			<key>name</key>
			<string>markup.raw.block.fenced.markdown</string>
		</dict>
		<key>grid-table</key>
		<dict>
			<key>begin</key>
			<string>^(\||\+)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>color.red</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?=(\1)$)</string>
			<key>name</key>
			<string>color.green markup.table.markdown</string>
			<key>patterns</key>
			<array/>
		</dict>
		<key>hash-tag</key>
		<dict>
			<key>match</key>
			<string>(?&lt;=^|\s)(@)[\w\d-]+</string>
			<key>name</key>
			<string>color.cyan markup.tag.at.markdo</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#tag-optional-value</string>
				</dict>
			</array>
		</dict>
		<key>heading</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#atx-heading</string>
				</dict>
			</array>
		</dict>
		<key>highlight</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.highlight.criticmarkup</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>markup.highlight.criticmarkup</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.highlight.criticmarkup</string>
				</dict>
			</dict>
			<key>match</key>
			<string>({==)(.*?)(==})(?={&gt;&gt;.*?&lt;&lt;})</string>
			<key>name</key>
			<string>meta.highlight.criticmarkup</string>
		</dict>
		<key>horizontal-rule</key>
		<dict>
			<key>comment</key>
			<string>*** or --- or ___ or somesuch</string>
			<key>match</key>
			<string>^(\s*[_\-\*]\s*){3,}$</string>
			<key>name</key>
			<string>markup.separator.markdown</string>
		</dict>
		<key>indented-code</key>
		<dict>
			<key>begin</key>
			<string>^([ ]{4}|\t)</string>
			<key>end</key>
			<string>$</string>
			<key>name</key>
			<string>markup.raw.block.indented.markdown</string>
		</dict>
		<key>inline</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#backslash-escape</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#inline-code</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#bold</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#italic</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#strikethrough</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#inline-link</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#inline-reference-link</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#link-url</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#link-email</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#critic-markup</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#valid-markdown</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#etcetera</string>
				</dict>
			</array>
		</dict>
		<key>inline-code</key>
		<dict>
			<key>begin</key>
			<string>(`{1,2})(.*?)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.raw.inline.markdown</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(\1)</string>
			<key>name</key>
			<string>markup.raw.inline.markdown</string>
		</dict>
		<key>inline-link</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.link.inline.markdown</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>string.other.link.inline.markdown</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.link.inline.markdown</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>markup.underline.link.url.markdown</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>string.other.link.title.markdown</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.link.inline.markdown</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(!?\[)(.*?)(\]\()(\S+)\s*(".*?")?\s*(\))</string>
			<key>name</key>
			<string>meta.link.inline.markdown</string>
		</dict>
		<key>inline-reference-link</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.link.inline.markdown</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>string.other.link.inline.markdown</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.link.inline.markdown</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>markup.underline.link.reference.markdown</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.link.inline.markdown</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(!?\[)(.*?)(\][ ]?\[)(.*?)(\])</string>
			<key>name</key>
			<string>meta.link.inline.reference.markdown</string>
		</dict>
		<key>italic</key>
		<dict>
			<key>begin</key>
			<string>(\*|_)(.*?)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.italic.markdown</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>*italic* or _strong_</string>
			<key>end</key>
			<string>(\1)</string>
			<key>name</key>
			<string>markup.italic.markdown</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#inline</string>
				</dict>
			</array>
		</dict>
		<key>link-definition</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.link.inline.markdown</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>markup.underline.link.reference</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.link.inline.markdown</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>markup.underline.link.url.markdown</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>string.other.link.title.markdown</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^[ ]{0,3}(\[)(.*?)(\]:)\s+(\S+)\s*(["'\(].*?["'\)])?</string>
			<key>name</key>
			<string>meta.link.definition.markdown</string>
		</dict>
		<key>link-email</key>
		<dict>
			<key>match</key>
			<string>([a-z0-9_\.-]+)@([\da-z\.-]+)\.([a-z\.]{2,6})</string>
			<key>name</key>
			<string>markup.underline.link.email.markdown</string>
		</dict>
		<key>link-url</key>
		<dict>
			<key>match</key>
			<string>(https?:\/\/)([\da-z\.-]+)\.([a-z\.]{2,6})([\/\w\.\-\?=&amp;#\+]*)*\/?</string>
			<key>name</key>
			<string>markup.underline.link.url.markdown</string>
		</dict>
		<key>list</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#task-list</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#unordered-list</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#ordered-list</string>
				</dict>
			</array>
		</dict>
		<key>ordered-list</key>
		<dict>
			<key>begin</key>
			<string>^\s*(#\.|(\d+|[A-z]|[IVXLCDM]+|[ivxlcdm]+)[\.\)]|\((\d+|[A-z]|[IVXLCDM]+|[ivxlcdm]+)\)|\(\@[\w\-]*\))\s+</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.list.ordered.markdown</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(\n|$)</string>
			<key>name</key>
			<string>markup.list.ordered.markdown</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#inline</string>
				</dict>
			</array>
		</dict>
		<key>paragraph</key>
		<dict>
			<key>begin</key>
			<string>^</string>
			<key>end</key>
			<string>\n</string>
			<key>name</key>
			<string>meta.paragraph.markdown</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#inline</string>
				</dict>
			</array>
		</dict>
		<key>setex-heading</key>
		<dict>
			<key>begin</key>
			<string>^(test)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>markup.deleted.criticmarkup</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.heading.markdown</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(=)(?=\n)</string>
			<key>name</key>
			<string>markup.heading.markdown</string>
		</dict>
		<key>strikethrough</key>
		<dict>
			<key>begin</key>
			<string>(\~\~|__)(.*?)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.strikethrough.markdown</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(\1)</string>
			<key>name</key>
			<string>markup.strikethrough.markdown</string>
		</dict>
		<key>substitution</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.changed.criticmarkup</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>markup.changed.criticmarkup</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.changed.criticmarkup</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>markup.changed.criticmarkup</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.changed.criticmarkup</string>
				</dict>
			</dict>
			<key>match</key>
			<string>({~~)(.+?)(~&gt;)(.+?)(~~})</string>
			<key>name</key>
			<string>meta.substitution.criticmarkup</string>
		</dict>
		<key>table</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#grid-table</string>
				</dict>
			</array>
		</dict>
		<key>table-cell</key>
		<dict>
			<key>begin</key>
			<string>\G(.*?)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>color.blue</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>color.red</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?=(\||\+|$|\n))</string>
			<key>name</key>
			<string>markup.table.cell.markdown</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#inline</string>
				</dict>
			</array>
		</dict>
		<key>table-separator</key>
		<dict>
			<key>begin</key>
			<string>((-|=)+)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>color.yellow</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>color.red</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?=(\1)$)</string>
			<key>name</key>
			<string>markup.table.separator.markdown</string>
		</dict>
		<key>tag</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#at-tag</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#hash-tag</string>
				</dict>
			</array>
		</dict>
		<key>tag-optional-value</key>
		<dict>
			<key>match</key>
			<string>\G(\([\w\d-]+\))</string>
			<key>name</key>
			<string>markup.tag.optional-value.markdo</string>
		</dict>
		<key>task-list</key>
		<dict>
			<key>begin</key>
			<string>^\s*([-\+\*])\s+(?=\[[ xX]\])</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.list.task.markdown</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(\n|$)</string>
			<key>name</key>
			<string>markup.list.task.markdown</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\G\[[xX]\]</string>
					<key>name</key>
					<string>punctuation.definition.list.task.checkbox.complete.markdown</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\G\[ \]</string>
					<key>name</key>
					<string>punctuation.definition.list.task.checkbox.incomplete.markdown</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#inline</string>
				</dict>
			</array>
		</dict>
		<key>unordered-list</key>
		<dict>
			<key>begin</key>
			<string>^\s*([-\+\*])\s+</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.list.unordered.markdown</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(\n|$)</string>
			<key>name</key>
			<string>markup.list.unordered.markdown</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#inline</string>
				</dict>
			</array>
		</dict>
		<key>valid-markdown</key>
		<dict>
			<key>match</key>
			<string>&amp;</string>
			<key>name</key>
			<string>markup.other.valid.markdown</string>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>text.html.markdown</string>
	<key>uuid</key>
	<string>ac344730-1a2b-11e3-8ffd-0800200c9a66</string>
</dict>
</plist>
